sudo: required

language: cpp

compiler: gcc
dist: trusty

services:
  - docker

before_install:
  - docker pull brichards64/test
  - docker run -v `pwd`:/root/outfolder brichards64/test /bin/sh -c "cd /root/HyperK; ls; source /root/HyperK/env-WCSim.sh; cd /root/outfolder; make clean; make rootcint; make > /root/outfolder/testlog; echo hello > bentest"

script:
  - if [ -e bentest ]; then true; else false; fi