sudo: required

language: cpp

compiler: gcc
dist: trusty

services:
  - docker

before_install:
  - docker pull brichards64/wcsim
  - docker run -v `pwd`:/root/HyperK/WCSim brichards64/wcsim /bin/sh -c " source /root/HyperK/env-WCSim.sh; cd /root/HyperK/WCSim; make clean; make rootcint; make;  ls"
  - docker run -v `pwd`:/root/HyperK/WCSim brichards64/wcsim /bin/sh -c "source /root/HyperK/env-WCSim.sh; cd /root/HyperK/WCSim; ./exe/bin/Linux-g++/WCSim WCSim.mac"


script:
  - if [ -e ./exe/bin/Linux-g++/WCSim ]; then true; else false; fi
  - if [ -e wcsim.rootd ]; then true; else false; fi

notifications:
  email:
    recipients:
      - b.richards@qmul.ac.uk
    on_success: never # default: change
    on_failure: always # default: always